
---

- name: install apache and upload my web page
  hosts: all
  become: yes


  vars:
   source_file: ./MyWebPage/index.html
   destin_file: /var/www/html


  tasks:
  - name: install Apache Web Server
    apt: name=apache2 state=latest

  - name: copy MyHomePage to servers
    copy: src={{ source_file }}  dest={{ destin_file }} mode=0555
    notify: restart apache

  - name: start Web Servers and make it enable on boot
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: restart apache
    service: name=apache2 state=started
